repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v1.6.0
  hooks:
  - id: autopep8
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args: ['--ignore=E501']
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.1.0
  hooks:
  - id: reorder-python-imports
